// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXYFmHoBqIWtS3-wXzeStf4cWXEAFb44',
    appId: '1:753577900079:web:f9df18d43d6802ebbdeeda',
    messagingSenderId: '753577900079',
    projectId: 'fightfitness-8df7e',
    authDomain: 'fightfitness-8df7e.firebaseapp.com',
    storageBucket: 'fightfitness-8df7e.appspot.com',
    measurementId: 'G-D2QTY66E9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lPoXWH8Bc-aGKmCvlSFAfWXbWl1hBEQ',
    appId: '1:753577900079:android:6a2139e9e2edd3a2bdeeda',
    messagingSenderId: '753577900079',
    projectId: 'fightfitness-8df7e',
    storageBucket: 'fightfitness-8df7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQywTGVfwX1i5za_x_06lobMFUcy8zFs',
    appId: '1:753577900079:ios:d7a1a761a9677c72bdeeda',
    messagingSenderId: '753577900079',
    projectId: 'fightfitness-8df7e',
    storageBucket: 'fightfitness-8df7e.appspot.com',
    iosBundleId: 'com.example.fightfitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQywTGVfwX1i5za_x_06lobMFUcy8zFs',
    appId: '1:753577900079:ios:2822a00a8f523bbabdeeda',
    messagingSenderId: '753577900079',
    projectId: 'fightfitness-8df7e',
    storageBucket: 'fightfitness-8df7e.appspot.com',
    iosBundleId: 'com.example.fightfitness.RunnerTests',
  );
}
